package com.yusong.photosearch.Models;


/*
* Generated by http://www.jsonschema2pojo.org/
*
* */

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;
import android.support.annotation.NonNull;


import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import static com.yusong.photosearch.utilities.Constants.API_KEY;

@Entity(tableName = "photos")
public class Photo  {

    @PrimaryKey(autoGenerate = false)
    @NonNull
    @SerializedName("id")
    @Expose
    private String id;
    @SerializedName("owner")
    @Expose
    private String owner;
    @SerializedName("secret")
    @Expose
    private String secret;
    @SerializedName("server")
    @Expose
    private String server;
    @SerializedName("farm")
    @Expose
    private Integer farm;
    @SerializedName("title")
    @Expose
    private String title;
    @SerializedName("ispublic")
    @Expose
    private Integer ispublic;
    @SerializedName("isfriend")
    @Expose
    private Integer isfriend;
    @SerializedName("isfamily")
    @Expose
    private Integer isfamily;

    /**
     * No args constructor for use in serialization
     *
     */
    @Ignore
    public Photo() {
    }

    /**
     *
     * @param isfamily
     * @param farm
     * @param id
     * @param title
     * @param ispublic
     * @param owner
     * @param secret
     * @param server
     * @param isfriend
     */
    public Photo(String id, String owner, String secret, String server, Integer farm, String title, Integer ispublic, Integer isfriend, Integer isfamily) {
        super();
        this.id = id;
        this.owner = owner;
        this.secret = secret;
        this.server = server;
        this.farm = farm;
        this.title = title;
        this.ispublic = ispublic;
        this.isfriend = isfriend;
        this.isfamily = isfamily;
    }

    public String getPhotoUrl(String size) {
        String imageUrl = String.format("https://farm%d.staticflickr.com/%s/%s_%s_%s.jpg", this.farm, this.server, this.id, this.secret, size);
        return imageUrl;
    }

    public String getDetailInfoUrl() {
        String detailInfoUrl = String.format("https://api.flickr.com/services/rest/?method=flickr.photos.getinfo&api_key=%s&photo_id=%s&format=json&nojsoncallback=1",
                API_KEY, this.id);
        return detailInfoUrl;

    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public String getSecret() {
        return secret;
    }

    public void setSecret(String secret) {
        this.secret = secret;
    }

    public String getServer() {
        return server;
    }

    public void setServer(String server) {
        this.server = server;
    }

    public Integer getFarm() {
        return farm;
    }

    public void setFarm(Integer farm) {
        this.farm = farm;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getIspublic() {
        return ispublic;
    }

    public void setIspublic(Integer ispublic) {
        this.ispublic = ispublic;
    }

    public Integer getIsfriend() {
        return isfriend;
    }

    public void setIsfriend(Integer isfriend) {
        this.isfriend = isfriend;
    }

    public Integer getIsfamily() {
        return isfamily;
    }

    public void setIsfamily(Integer isfamily) {
        this.isfamily = isfamily;
    }

}

/*
@Entity(tableName = "photos")
public class Photo  {
    @PrimaryKey(autoGenerate = false)
    @NonNull
    private String id;

    private String owner;

    private String server;

    private String ispublic;

    private String isfriend;

    private String farm;

    private String secret;

    private String title;

    private String isfamily;


    @Ignore
    public Photo() {

    }
    public Photo(String owner, String server, String ispublic, String isfriend, String farm, String id, String secret, String title, String isfamily) {
        this.owner = owner;
        this.server = server;
        this.ispublic = ispublic;
        this.isfriend = isfriend;
        this.farm = farm;
        this.id = id;
        this.secret = secret;
        this.title = title;
        this.isfamily = isfamily;
    }

    public String getOwner ()
    {
        return owner;
    }

    public void setOwner (String owner)
    {
        this.owner = owner;
    }

    public String getServer ()
    {
        return server;
    }

    public void setServer (String server)
    {
        this.server = server;
    }

    public String getIspublic ()
    {
        return ispublic;
    }

    public void setIspublic (String ispublic)
    {
        this.ispublic = ispublic;
    }

    public String getIsfriend ()
    {
        return isfriend;
    }

    public void setIsfriend (String isfriend)
    {
        this.isfriend = isfriend;
    }

    public String getFarm ()
    {
        return farm;
    }

    public void setFarm (String farm)
    {
        this.farm = farm;
    }

    public String getId ()
    {
        return id;
    }

    public void setId (String id)
    {
        this.id = id;
    }

    public String getSecret ()
    {
        return secret;
    }

    public void setSecret (String secret)
    {
        this.secret = secret;
    }

    public String getTitle ()
    {
        return title;
    }

    public void setTitle (String title)
    {
        this.title = title;
    }

    public String getIsfamily ()
    {
        return isfamily;
    }

    public void setIsfamily (String isfamily)
    {
        this.isfamily = isfamily;
    }

    @Override
    public String toString() {
        return "ClassPojo [owner = "+owner+", " +
                "server = "+server+", " +
                "ispublic = "+ispublic+", " +
                "isfriend = "+isfriend+", " +
                "farm = "+farm+", " +
                "id = "+id+", " +
                "secret = "+secret+", " +
                "title = "+title+", " +
                "isfamily = "+isfamily+"]";
    }
}
*/

